name: props
description: Load properties format in dart or flutter. Just do it. Api is simple.
version: 2.0.0
homepage: https://github.com/fluttercandies/properties

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
